name: Export, encrypt, and deploy
on:
    push:
        branches:
            - gh-pages
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install staticrypt
              run: npm install -g staticrypt@3.*           
            - name: Encrypt with Staticrypt
              run: |
                staticrypt index.html -p benlauren27
                --template-title "Login To Our Wedding Site"
                --template-instructions "Enter the password from your invitation"