name: Export, encrypt, and deploy
on:
    push:
        branches:
            - gh-pages
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install staticrypt
              run: npm install -g staticrypt@3.*
            - name: Encrypt with Staticrypt
              run: >
                staticrypt Ben-Lauren2027/* -r -d Ben-Lauren2027 -p benlauren27 --short