name: Export, encrypt, and deploy
on:
    push:
        branches:
            - gh-pages
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install staticrypt
              run: npm install staticrypt            
            - name: Encrypt with Staticrypt
              run: |
                staticrypt Ben-Lauren2027/* -r -d Ben-Lauren2027 \
                --password benlauren27 \
                --template-title "Our Wedding" \
                --template-instructions "Enter the password from your invitation" \